package com.hisen.mybatis.mapper;

import com.hisen.mybatis.model.Appointment;
import com.hisen.mybatis.model.AppointmentExample;
import com.hisen.mybatis.model.AppointmentKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

/**
 * MyBatis-generator自动生成
 */
public interface AppointmentMapper {

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table appointment
   *
   * @mbggenerated Wed Mar 22 09:54:59 CST 2017
   */
  int countByExample(AppointmentExample example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table appointment
   *
   * @mbggenerated Wed Mar 22 09:54:59 CST 2017
   */
  int deleteByExample(AppointmentExample example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table appointment
   *
   * @mbggenerated Wed Mar 22 09:54:59 CST 2017
   */
  int deleteByPrimaryKey(AppointmentKey key);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table appointment
   *
   * @mbggenerated Wed Mar 22 09:54:59 CST 2017
   */
  int insert(Appointment record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table appointment
   *
   * @mbggenerated Wed Mar 22 09:54:59 CST 2017
   */
  int insertSelective(Appointment record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table appointment
   *
   * @mbggenerated Wed Mar 22 09:54:59 CST 2017
   */
  List<Appointment> selectByExample(AppointmentExample example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table appointment
   *
   * @mbggenerated Wed Mar 22 09:54:59 CST 2017
   */
  Appointment selectByPrimaryKey(AppointmentKey key);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table appointment
   *
   * @mbggenerated Wed Mar 22 09:54:59 CST 2017
   */
  int updateByExampleSelective(@Param("record") Appointment record,
      @Param("example") AppointmentExample example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table appointment
   *
   * @mbggenerated Wed Mar 22 09:54:59 CST 2017
   */
  int updateByExample(@Param("record") Appointment record,
      @Param("example") AppointmentExample example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table appointment
   *
   * @mbggenerated Wed Mar 22 09:54:59 CST 2017
   */
  int updateByPrimaryKeySelective(Appointment record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table appointment
   *
   * @mbggenerated Wed Mar 22 09:54:59 CST 2017
   */
  int updateByPrimaryKey(Appointment record);
}