CREATE OR REPLACE NONEDITIONABLE FUNCTION GET_DATE_FROM_MILLISECOND(MILLISECOND NUMBER)
RETURN DATE IS
  Result DATE;
BEGIN
	--in  1149124496734
	--out date

	SELECT (TRUNC(SYSDATE,'HH')+(MILLISECOND-(GET_MILLISECOND(TRUNC(SYSDATE,'HH'))))/86400000)
	INTO Result
	FROM DUAL;

	RETURN Result;

END GET_DATE_FROM_MILLISECOND;
/
