package com.hisen.mybatis.model;

import java.util.Date;

/**
 * MyBatis-generator自动生成
 */
public class Appointment extends AppointmentKey {

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column appointment.appoint_time
   *
   * @mbggenerated Wed Mar 22 09:54:59 CST 2017
   */
  private Date appointTime;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column appointment.appoint_time
   *
   * @return the value of appointment.appoint_time
   * @mbggenerated Wed Mar 22 09:54:59 CST 2017
   */
  public Date getAppointTime() {
    return appointTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column appointment.appoint_time
   *
   * @param appointTime the value for appointment.appoint_time
   * @mbggenerated Wed Mar 22 09:54:59 CST 2017
   */
  public void setAppointTime(Date appointTime) {
    this.appointTime = appointTime;
  }
}